/** DO NOT EDIT! This file is generated by @svelte-put/inline-svg vite plugin */
declare module 'svelte/elements' {
	export interface SVGAttributes {
		'inline-src'?:
			| `./${string}`
			| `../${string}`
			| 'chim-lac'
			| 'dong-thai-binh-hung-bao'
			| 'svelte'
			| 'sveltevietnam'
			| 'tu-chu'
			| 'tu-nom';
	}
}
export {};
