/** DO NOT EDIT! This file is generated by @svelte-put/inline-svg vite plugin */
declare module 'svelte/elements' {
	export interface SVGAttributes {
		'inline-src'?:
			| `./${string}`
			| `../${string}`
			| 'au-lac'
			| 'dong'
			| 'svelte'
			| 'sveltevietnam'
			| 'tu_chu'
			| 'tu_nom';
	}
}
export {};
