/** DO NOT EDIT! This file is generated by vite-plugin-sveltekit-routing */
declare namespace App {
	export type RouteKey = 'home' | 'blog/:slug' | 'blog' | 'design';
	export type Route = {
		path: string;
		name: string;
	};
}