// DO NOT EDIT! This file is generated by vite-plugin-sveltekit-routing

declare namespace App {
	export type RouteKey = 'home' | 'blog/:slug' | 'blog' | 'blog/categories' | 'blog/series' | 'code-of-conduct' | 'design' | 'events' | 'jobs' | 'roadmap' | 'search' | 'settings' | 'sponsor';
	export type Route = {
		path: string;
		name: string;
	};
}