import type { Component, Snippet } from 'svelte';

/**
 * context provider for i18n
 */
export interface ProviderProps {
	/**
	 * the current language of the app,
	 * updates to this prop should propagate to all `T.svelte` instances
	 */
	lang: string;
	/**
	 * a custom `sanitize` function to sanitize the message content before rendering,
	 * @default import('sanitize-html').default
	 */
	sanitize?: (content: string) => string;
	// /**
	//  * a custom `query` remote function to fetch message in "remote" mode
	//  * @default (await import('$i18n/i18n.remote.js')).getMessage // (generated by vite plugin)
	//  */
	// remote?: ???;
	children: Snippet;
}

export const Provider: Component<ProviderProps>;
