/**
 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

import { createMessageWithParams } from "@sveltevietnam/i18n/runtime/factory";

const _greet = createMessageWithParams("greet", /**@type {(params: Record<"name"|"unreadCount", string>) => string}*/ (params => `Hello, ${params.name}! You have ${params.unreadCount} unread messages.`));
export { _greet as "greet" };
