packages:
  - packages/*
  - packages/i18n/tests/e2e/*
  - services/*
  - sites/*
  - workers/*
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
minimumReleaseAge: 4320 # 3 days in minutes
minimumReleaseAgeExclude:
  - svelte
  - '@sveltejs/kit'
  - '@sveltejs/adapter-cloudflare'
  - '@sveltejs/enhanced-image'
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - '@iconify/tools@4.1.4'
  - undici@6.22.0
updateConfig:
  ignoreDependencies:
    # do not upgrade until this issue is fixed: https://github.com/paralleldrive/cuid2/issues/112
    - '@paralleldrive/cuid2'
