packages:
  - packages/*
  - packages/i18n/tests/e2e/*
  - services/*
  - sites/*
  - workers/*
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
minimumReleaseAge: 4320 # 3 days in minutes
minimumReleaseAgeExclude:
  - svelte
  - '@sveltejs/kit'
  - '@sveltejs/adapter-cloudflare'
  - '@sveltejs/enhanced-image'
trustPolicy: no-downgrade
