packages:
  - 'packages/*'
  - 'packages/i18n/tests/e2e/*'
  - 'services/*'
  - 'sites/*'
  - 'workers/*'
minimumReleaseAge: 4320 # 3 days in minutes
minimumReleaseAgeExclude:
  - svelte
  - '@sveltejs/kit'
  - '@sveltejs/adapter-cloudflare'
