import dedent from 'dedent';
import { test, expect } from 'vitest';

import { createMessage } from '$tests/utils';

import { generateMessageModule } from '.';

const js = dedent;
const langs = ['vi', 'en'];

test('no message should return empty string', () => {
	expect(generateMessageModule([], langs)).toBe('');
});

test('can generate module with only simple message', () => {
	const messages = [createMessage('greeting', 'Hello, world!')];
	const mod = generateMessageModule(messages, langs);
	expect(mod).toEqual(js`
		/**
		 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

		import { createMessageSimple } from "@sveltevietnam/i18n/runtime/factory";

		import * as en from "./en.js";
		import * as vi from "./vi.js";

		const _greeting = /*@__PURE__*/ createMessageSimple("greeting", {
		    en: en["greeting"],
		    vi: vi["greeting"]
		})
		export { _greeting as "greeting" };\n
	`);
});

test('can generate module with only with-params message', () => {
	const messages = [createMessage('farewell', 'Goodbye {{name}}')];
	const mod = generateMessageModule(messages, langs);
	expect(mod).toEqual(js`
		/**
		 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

		import { createMessageWithParams } from "@sveltevietnam/i18n/runtime/factory";

		import * as en from "./en.js";
		import * as vi from "./vi.js";

		const _farewell = /*@__PURE__*/ createMessageWithParams("farewell", {
		    en: en["farewell"],
		    vi: vi["farewell"]
		})
		export { _farewell as "farewell" };\n
	`);
});

test('can generate module with all types of message', () => {
	const messages = [
		createMessage('greeting', 'Hello, world!'),
		createMessage('farewell', 'Goodbye {{name}}'),
	];
	const mod = generateMessageModule(messages, langs);
	expect(mod).toEqual(js`
		/**
		 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

		import { createMessageSimple, createMessageWithParams } from "@sveltevietnam/i18n/runtime/factory";

		import * as en from "./en.js";
		import * as vi from "./vi.js";

		const _greeting = /*@__PURE__*/ createMessageSimple("greeting", {
		    en: en["greeting"],
		    vi: vi["greeting"]
		})
		const _farewell = /*@__PURE__*/ createMessageWithParams("farewell", {
		    en: en["farewell"],
		    vi: vi["farewell"]
		})
		export { _greeting as "greeting", _farewell as "farewell" };\n
	`);
});
