name: EN - 📜 Proposal for Blog Post Publication
description: Propose a blog post to be published at *https://sveltevietnam.dev/blog*
title: "Blog Post Proposal: <short title of blog post>"
labels:
  - "page:blog"
  - "content:blog"
  - "blog:pending"
assignees:
  - vnphanquang
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being part of the community. Let's write some stuff, shall we?

        ## Note

        This is a **no-code** proposal for blog post. If approved your blog post will be implemented by maintainers.  If you want granular control or prefer to code yourself, refer to [Blog Post Implementation Guidelines](https://github.com/sveltevietnam/sveltevietnam.dev/blob/main/docs/DEV_BLOG_POST.md) and open a PR that directly implements your post.

        It is recommended that you provide and Vietnamese translation for each of the field and information below. If you are not able to do so, leave a comment below so that administrators and others from our community can help out.

  - type: markdown
    attributes:
      value: |
        ## Authors

        Provide information about the author(s) using the format below

        ```
        Nguyễn A / A Nguyễn:

        - Title for display: Developer Advocate at Company C
        - Avatar URL: ...
        - Social links:
            - twitter: https://twitter.com/example-nguyenvana
            - github: https://github.com/example-nguyenvana
            - linkedin: https://linkedin.com/in/example-nguyenvana
            - personal website: https://example-nguyenvana.dev

        # ... other co-authors with the same format as above (if any)
        ```
  - type: textarea
    id: authors-en
    attributes:
      label: Authors (English)
      value: As instructed above
    validations:
      required: false
  - type: textarea
    id: authors-vi
    attributes:
      label: Authors (Vietnamese)
      value: As instructed above
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Slug

        Provide an optional slug. Leave blank to auto-generate from title.
        Slug must be provided in English and is reused for both Vietnamese and English versions.
  - type: input
    id: slug
    attributes:
      label: Slug
      placeholder: my-blog-post-about-something
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Title

        Provide a title for the blog post, used in page and for meta tags
  - type: input
    id: title-en
    attributes:
      label: Title (English)
      placeholder: My blog post title
    validations:
      required: false
  - type: input
    id: title-vi
    attributes:
      label: Title (Vietnamese)
      placeholder: Bài viết của tôi
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Description

        A short description about the blog post, used for meta tags and display in blog post listing
  - type: input
    id: description-en
    attributes:
      label: Description (English)
      placeholder: My blog post about Svelte Vietnam
    validations:
      required: false
  - type: input
    id: description-vi
    attributes:
      label: Description (Vietnamese)
      placeholder: Bài viết hay ho về Svelte Việt Nam
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Keywords

        Provide an optional comma-separated list of keywords, used for meta tags
  - type: input
    id: keywords-en
    attributes:
      label: Keywords (English)
      placeholder: typescript, benchmark, UI, ...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Tags

        Select one or more tags to help categorize blog post
  - type: dropdown
    id: tags-en
    attributes:
      label: Tags
      multiple: true
      options:
        - svelte
        - kit
        - ecosystem
        - tooling
        - community
        - inside
        - technical
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Content

        Provide the content for this blog post. You may use Markdown syntax. If the content is long, prefer an attachment instead. Attachment or link to your blog post content. For example: content.md, content.docx, link to Figma, Google Docs, ...
  - type: textarea
    id: content-en
    attributes:
      label: Content (English)
      value: As instructed above
    validations:
      required: false
  - type: textarea
    id: content-vi
    attributes:
      label: Content (Vietnamese)
      value: As instructed above
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Additional Information

        You may include any relevant information, for example optimized image links or a design guideline on how the post should be implemented.
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Thank you

        Administrators will review your content and update progress in this issue.
        If approved, this post will be published to *https://sveltevietnam.dev/blog*.
