name: "EN - \U0001F41E Bug report"
description: Report a bug at sveltevietnam.dev
title: "Bug Report: <short description>"
labels:
  - "op:triage"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being part of the community. Let's fill out some information to help maintainers better understand the issue.

        ## Note

        Sometimes it takes a hard refresh for the site to be fully updated with new version.

        ## Report Details
  - type: input
    id: version
    attributes:
      label: Version of sveltevietnam.dev
      description: |
        Find the site version at the bottom left of the page, inside the footer.

        ![site version location](https://github.com/sveltevietnam/sveltevietnam.dev/blob/main/.github/assets/site_version_location.png?raw=true)
      placeholder: semantic#hash@timestamp
    validations:
      required: true
  - type: textarea
    id: system
    attributes:
      label: System Information
      description: Provide your system and environment information.
      value: |
        - Operating System: Windows | MacOS | Ubuntu
        - Browser: Chrome | Firefox | Safari | Edge
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Include steps to reproduce, you may include screenshots or videos.
      value: |
        ### Steps to reproduce

        1. Go to page `/...`,
        2. Click on button ...

        ### Expected behavior

        ...

        ### Actual behavior

        ...

        <screenshots_or_videos>
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
  - type: markdown
    attributes:
      value: |
        ## Thank you

        We appreciate your effort to make the site better!
