name: EN - 📜 Proposal for Blog Post Publication
description: Propose a blog post to be published at *https://sveltevietnam.com/blog*
title: "Blog Post Proposal: <short title of blog post>"
labels:
  - "page:blog"
  - "content:blog"
  - "blog:pending"
assignees:
  - vnphanquang
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being part of the community. Let's write some stuff, shall we?

        ## Note

        This is a **no-code** proposal for blog post. If approved your blog post will be implemented by maintainers.

        If you want granular control or prefer to code yourself, refer to [Blog Post Implementation Guidelines](https://github.com/sveltevietnam/sveltevietnam.dev/blob/main/docs/DEV_BLOG_POST.md) and open a PR that directly implements your post.

        ## Proposal Details

  - type: input
    id: translation
    attributes:
      label: Link to the accompanying issue for the Vietnamese version (if any).
      description: |
        This issue is a proposal for the English version of your post. It is recommended that you use the template [VI - Đề nghị đăng bài](https://github.com/sveltevietnam/sveltevietnam.dev/issues/new/choose) to provide and link a Vietnamese translation.

        If you are not able to do so, leave a comment below so that administrators and others from our community can help out.
      placeholder: https://github.com/sveltevietnam/sveltevietnam.dev/issues/XXX
    validations:
      required: false

  - type: textarea
    id: authors
    attributes:
      label: Authors
      description: Provide information about the author(s) using the format below
      value: |
        Nguyễn Văn A:

        - Title for display: Developer Advocate at Company C
        - Avatar URL: ...
        - Social links:
            - twitter: https://twitter.com/example-nguyenvana
            - github: https://github.com/example-nguyenvana
            - linkedin: https://linkedin.com/in/example-nguyenvana
            - personal website: https://example-nguyenvana.dev

        # ... other co-authors with the same format as above (if any)
    validations:
      required: true
  - type: input
    id: slug
    attributes:
      label: Slug
      description: |
        Provide an optional slug. Leave blank to auto-generate from title.
        Slug must be provided in English and is reused for both Vietnamese and English versions.
      placeholder: my-blog-post-about-something
    validations:
      required: false
  - type: input
    id: title
    attributes:
      label: Title
      description: Provide a title for the blog post, used in page and for meta tags
      placeholder: My blog post title
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: A short description about the blog post, used for meta tags and display in blog post listing
      placeholder: My interesting blog post about Svelte Vietnam
    validations:
      required: true
  - type: input
    id: keywords
    attributes:
      label: Keywords
      description: Provide an optional comma-separated list of keywords, used for meta tags
      placeholder: typescript, benchmark, UI, ...
    validations:
      required: true
  - type: dropdown
    id: tags
    attributes:
      label: Tags
      description: Select one or more tags to help categorize blog post
      multiple: true
      options:
        - svelte
        - kit
        - ecosystem
        - tooling
        - community
    validations:
      required: false
  - type: textarea
    id: content
    attributes:
      label: Post Content
      description: Provide the content for this blog post. You may use Markdown syntax. If the content is long, prefer an attachment instead.
      value: |
        Attachment or link to your blog post content. For example: content.md, content.docx, link to Figma, Google Docs, ...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: You may include any relevant information, for example optimized image links or a design guideline on how the post should be implemented.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Thank you

        Administrators will review your content and update progress in this issue.
        If approved, this post will be published to *https://sveltevietnam.com/blog*.
