name: EN - 🖇️ Request to Link External Blog Post
description: Request that a link to an external blog post be added to *https://sveltevietnam.dev/blog*
title: "External Blog Post Link Request: <short title of blog post>"
labels:
  - "page:blog"
  - "content:blog"
assignees:
  - vnphanquang
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being part of the community.

        ## Note

        Typically, the content of the requested blog post should be relevant to Svelte and the Svelte Vietnam community.

        Note that the content of the linked blog post will stay on its original site and will not be copied to *sveltevietnam.dev*; only a link is added. To propose blog post whose content is published on *sveltevietnam.dev* itself, use the [EN - Proposal for Blog Post Publication](https://github.com/sveltevietnam/sveltevietnam.dev/issues/new/choose) instead.

  - type: markdown
    attributes:
      value: |
        ## Link

        Request must include at least one of the following link.
  - type: input
    id: link-en
    attributes:
      label: Link (English)
      placeholder: link to dev.to, personal blog, ...
    validations:
      required: false
  - type: input
    id: link-vi
    attributes:
      label: Link (Vietnamese)
      placeholder: link to dev.to, personal blog, ...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Author

        Author name to display in the linked post
  - type: input
    id: author-en
    attributes:
      label: Author (English)
      placeholder: Phương Trần
    validations:
      required: false
  - type: input
    id: author-vi
    attributes:
      label: Author (Vietnamese)
      placeholder: Trần Phương
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Description

        A short description about the blog post or display in the linked post
  - type: input
    id: description-en
    attributes:
      label: Description (English)
      placeholder: My blog post about Svelte
    validations:
      required: false
  - type: input
    id: description-vi
    attributes:
      label: Description (Vietnamese)
      placeholder: Bài viết của tôi về Svelte
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Additional Information

        You may include any relevant information that you wish administrators to take note.
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Thank you

        Administrators will review your request and update progress in this issue.
        If approved, link to post will be listed at *https://sveltevietnam.dev/blog*.
