name: EN - 🖇️ Request to Link External Blog Post
description: Request that a link to an external blog post be added to *https://sveltevietnam.com/blog*
title: "External Blog Post Link Request: <short title of blog post>"
labels:
  - "page:blog"
  - "content:blog"
assignees:
  - vnphanquang
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being part of the community.

        ## Note

        Typically, the content of the requested blog post should be relevant to Svelte and the Svelte Vietnam community.

        Note that the content of the linked blog post will stay on its original site and will not be copied to *sveltevietnam.dev*; only a link is added. To propose blog post whose content is published on *sveltevietnam.dev* itself, use the [EN - Proposal for Blog Post Publication](https://github.com/sveltevietnam/sveltevietnam.dev/issues/new/choose) instead.

        ## Request Details

        Request must include at least one of the following link.
  - type: input
    id: link-en
    attributes:
      label: Link to external blog post in English (if any)
      placeholder: link to dev.to, personal blog, ...
    validations:
      required: false
  - type: input
    id: link-vi
    attributes:
      label: Link to external blog post in Vietnamese (if any)
      placeholder: link to dev.to, personal blog, ...
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: You may include any relevant information that you wish administrators to take note.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Thank you

        Administrators will review your request and update progress in this issue.
        If approved, link to post will be listed at *https://sveltevietnam.com/blog*.
