name: VI - 📜 Đề nghị đăng bài
description: Đề nghị đăng bài mới tại *https://sveltevietnam.dev/blog*
title: "Đề nghị đăng bài: <tựa đề bài viết>"
labels:
  - "page:blog"
  - "content:blog"
  - "blog:pending"
assignees:
  - vnphanquang
body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã dành thời gian đóng góp cho cộng đồng.

        ## Lưu ý

        Trong bản đề nghị này, bạn không cần phải code. Nếu được phê duyệt, bài viết của bạn sẽ được code bởi các kỹ thuật viên. Tuy nhiên nếu bạn muốn tự code, hãy xem qua [Blog Post Implementation Guidelines](https://github.com/sveltevietnam/sveltevietnam.dev/blob/main/docs/DEV_BLOG_POST.md) và trực tiếp mở PR cho bài viết nhé.

        Ban quản trị khuyến khích bạn cung cấp thêm bản tiếng Anh cho mỗi thông tin và nội dung bên dưới. Nếu bạn không thể dịch hoặc cung cấp bản tiếng Anh, hãy để lại lời nhắn bên dưới để ban quản trị và cộng đồng cùng hỗ trợ nhé.

  - type: markdown
    attributes:
      value: |
        ## Tác giả

        Điền thông tin về (các) tác giả theo mẫu dưới

        ```
        Nguyễn A / A Nguyễn:

        - Title for display: Developer Advocate at Company C
        - Avatar URL: ...
        - Profile Link: https://github.com/example-nguyenvana

        # ... thêm đồng tác giả theo mẫu trên (nếu có)
        ```
  - type: textarea
    id: authors-vi
    attributes:
      label: Tác giả (tiếng Việt)
      value: Theo mẫu trên
    validations:
      required: false
  - type: textarea
    id: authors-en
    attributes:
      label: Tác giả (tiếng Anh)
      value: Theo mẫu trên
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Đường dẫn (slug)

        Điền slug tùy chọn. Để trống để tự động tạo từ tiêu đề.
        Riêng slug phải bằng tiếng anh và sẽ được sử dụng cho cả bản tiếng Anh và tiếng Việt.
  - type: input
    id: slug
    attributes:
      label: Slug
      placeholder: my-blog-post-about-something
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Tiêu đề

        Điền tiêu đề bài viết (dùng cho cả meta tags)
  - type: input
    id: title-vi
    attributes:
      label: Tiêu đề (tiếng Việt)
      placeholder: Tựa bài viết của tôi
    validations:
      required: false
  - type: input
    id: title-en
    attributes:
      label: Tiêu đề (tiếng Anh)
      placeholder: My blog post title
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Mô tả

        Điền mô tả ngắn gọn về bài viết (dùng cho meta tags và hiển thị trên danh sách bài viết)
  - type: input
    id: description-vi
    attributes:
      label: Mô tả (tiếng Việt)
      placeholder: Bài viết hay ho về Svelte Việt Nam
    validations:
      required: false
  - type: input
    id: description-en
    attributes:
      label: Mô tả (tiếng Anh)
      placeholder: My blog post about Svelte Vietnam
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Từ khoá (Keywords)

        Điền chuỗi các từ khoá, cách nhau bằng dấu phẩy (dùng cho meta tags). Ví dụ:

        ```
        typescript, benchmark, UI, ...
        ```
  - type: input
    id: keywords-vi
    attributes:
      label: Từ khoá (tiếng Việt)
    validations:
      required: false
  - type: input
    id: keywords-en
    attributes:
      label: Từ khoá (tiếng Anh)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Gắn thẻ (Tags)

        Chọn một hoặc nhiều thẻ thích hợp để phân loại bài viết
  - type: dropdown
    id: tags
    attributes:
      label: Gắn thẻ
      multiple: true
      options:
        - svelte
        - kit
        - ecosystem
        - tooling
        - community
        - inside
        - technical
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Nội dung

        Điền nội dung bài viết. Bạn có thể dùng cú pháp Markdown. Dùng file đính kèm cho bài viết dài. Đính kèm file hoặc đường dẫn tới nội dung bài viết. Ví dụ: content.md, content.docx, đường dẫn tới Figma, Google Docs, …
  - type: textarea
    id: content-vi
    attributes:
      label: Nội dung (tiếng Việt)
      value: Như hướng dẫn trên
    validations:
      required: false
  - type: textarea
    id: content-en
    attributes:
      label: Nội dung (tiếng Anh)
      value: Như hướng dẫn trên
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Thông tin bổ sung

        Thêm thông tin liên quan, ví dụ đường dẫn đến hình ảnh đã được tối ưu hoá, bản phát hoạ, thiết kế cho nội dung bài viết, hoặc hướng dẫn khác cho kỹ thuật viên
  - type: textarea
    id: additional
    attributes:
      label: Thông tin bổ sung
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Cảm ơn bạn!

        Ban quản trị sẽ xem xét và cập nhật thông tin vào issue này.
        Nếu được phê duyệt, bài viết sẽ được đăng tại trang
        *https://sveltevietnam.dev/blog*
