import dedent from 'dedent';
import { test, expect } from 'vitest';

import { generateConstantsModule } from '.';

const js = dedent;

test('can generate', () => {
	const mod = generateConstantsModule({
		langs: ['vi', 'en'],
		keys: ['welcome', 'goodbye', 'component.test'],
		mode: 'static',
	});
	expect(mod).toEqual(js`
		/**
		 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

		export const mode = /**@type {const}*/ ("static");
		export const langs = /**@type {const}*/ (["en", "vi"]);
		export const keys = /**@type {const}*/ (["welcome", "goodbye", "component.test"]);\n
	`);
});
