# fly.toml app configuration file generated for sveltevietnam-discord on 2023-08-22T13:53:41+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sveltevietnam-discord"
primary_region = "sin"

[build]

[http_service]
  internal_port = 5006
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
