/**
 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

import { createMessageSimple } from "@sveltevietnam/i18n/runtime/factory";

const _hello = /**@__PURE__*/ createMessageSimple("hello", (() => "Hello, world!"));
const _goodbye = /**@__PURE__*/ createMessageSimple("goodbye", (() => "Goodbye, world!"));
export { _hello as "hello", _goodbye as "goodbye" };
