/**
 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

import { createMessageSimple } from "@sveltevietnam/i18n/runtime/factory";

const _global_hello = /**@__PURE__*/ createMessageSimple("global.hello", (() => "Hello, world!"));
export { _global_hello as "global.hello" };
