d1_databases = [
	{ binding = "D1", database_name = "sv", database_id = "40b1cdbd-8467-43fd-bede-4e888069a78b", migrations_table = "d1_migrations", migrations_dir = "./src/migrations" },
]

[env.preview]
d1_databases = [
	{ binding = "D1", database_name = "sv", database_id = "b1070d05-9675-4d7b-86ef-91330ce9628d", migrations_table = "d1_migrations", migrations_dir = "./src/migrations" },
]

[env.production]
d1_databases = [
	{ binding = "D1", database_name = "sv", database_id = "fac75b01-e79d-44b8-a29c-e9793ec8ab9d", migrations_table = "d1_migrations", migrations_dir = "./src/migrations" },
]
