import dedent from 'dedent';

const ts = dedent;

// ===========
// Public API
// ===========
/**
 * @param {string} mode
 * @returns {string}
 */
export function generateDts(mode) {
	return ts`
		/**
		 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

		import type { langs } from "./constants";
		import type * as m from "./messages";
		declare module "@sveltevietnam/i18n-new/generated" {
		    export interface $$Runtime {
		        (): {
		            mode: "${mode}" as const;
		            mapping: typeof m;
		            languages: typeof langs;
		        };
		    }
		}`;
}
