import dedent from 'dedent';
import { test, expect } from 'vitest';

import { generateDts } from '.';

const ts = dedent;

test('can generate', () => {
	expect(generateDts('static')).equal(ts`
		/**
		 * DO NOT EDIT! This file is generated by @sveltevietnam/i18n */

		import type { langs } from "./constants";
		import type * as m from "./messages";
		declare module "@sveltevietnam/i18n/generated" {
		    export interface $$Runtime {
		        (): {
		            mode: "static";
		            mapping: typeof m;
		            languages: typeof langs;
		        };
		    }
		}
		declare module "@sveltevietnam/i18n/generated/messages" {
		    export * from "./messages";
		}
	`);
});
