import ts, { factory } from 'typescript';

export const newline = () => factory.createIdentifier('\n');

/**
 * @param {import('typescript').Node[]} nodes
 * @returns {string}
 */
export function print(nodes) {
	const doc = factory.createJSDocComment(
		'DO NOT EDIT! This file is generated by @sveltevietnam/i18n',
		undefined,
	);

	const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
	const resultFile = ts.createSourceFile(
		'temp.ts',
		'',
		ts.ScriptTarget.Latest,
		false,
		ts.ScriptKind.JS,
	);

	const code = printer.printList(
		ts.ListFormat.MultiLine,
		factory.createNodeArray([doc, newline(), ...nodes]),
		resultFile,
	);

	return code;
}
