name: Deploy @sites/www

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - preview
          - production

jobs:
  pre_jobs:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
      reason: ${{ steps.skip_check.outputs.reason }}
      mode: |-
        ${{
            inputs.environment
        ||  github.event_name == 'pull_request' && startsWith(github.head_ref, 'changeset-release/main') && github.event.pull_request.merged == true  && 'production'
        ||  github.event_name == 'pull_request' && startsWith(github.head_ref, 'changeset-release/main') && github.event.pull_request.merged == false && 'preview'
        ||                                                                                                                                               'dev'
        }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["workflow_dispatch"]'
          paths_filter: |
            www:
              paths:
                - 'internals/utils/**'
                - 'internals/isc/**'
                - 'sites/www/**'
  www:
    needs: pre_jobs
    if: (needs.pre_jobs.outputs.should_skip != 'true' && needs.pre_jobs.outputs.reason != 'paths') || (needs.pre_jobs.outputs.paths_result && !fromJSON(needs.pre_jobs.outputs.paths_result).www.should_skip)
    runs-on: ubuntu-latest
    env:
      npm_config_platform: linux
      npm_config_arch: x64
    environment:
      name: |-
        ${{
            needs.pre_jobs.outputs.mode == 'production' && '@sites/www|production'
        ||  needs.pre_jobs.outputs.mode == 'preview'    && '@sites/www|preview'
        ||                                                 '@sites/www|dev'
        }}
      url: |-
        ${{
            needs.pre_jobs.outputs.mode == 'production' && 'https://www.sveltevietnam.dev'
        ||  needs.pre_jobs.outputs.mode == 'preview'    && 'https://preview.sveltevietnam.dev'
        ||                                                  steps.cloudflare-pages-deploy.outputs.url
        }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Get pnpm cache
        uses: actions/cache@v3
        with:
          path: '${{ env.STORE_PATH }}'
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        continue-on-error: false

      - name: Rebuild sharp
        run: cd sites/www && npm rebuild sharp
        continue-on-error: false

      - name: Build
        run: pnpm run build --filter=@sites/www
        env:
          # TODO: rotate JWT_SECRET after 2024.04.20 (meetup event)
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          # cloudflare turnstile
          PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ vars.PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY }}
          CLOUDFLARE_TURNSTILE_SECRET_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}
          # cookies
          COOKIE_USER_ID: ${{ vars.COOKIE_USER_ID }}
          PUBLIC_COOKIE_SETTINGS_COLOR_SCHEME: ${{ vars.PUBLIC_COOKIE_SETTINGS_COLOR_SCHEME }}
          PUBLIC_COOKIE_SETTINGS_LANGUAGE: ${{ vars.PUBLIC_COOKIE_SETTINGS_LANGUAGE }}
          PUBLIC_COOKIE_SETTINGS_SPLASH: ${{ vars.PUBLIC_COOKIE_SETTINGS_SPLASH }}
          PUBLIC_COOKIE_SETTINGS_ACCESSIBILITY_REDUCE_MOTION: ${{ vars.PUBLIC_COOKIE_SETTINGS_ACCESSIBILITY_REDUCE_MOTION }}
          # public env
          PUBLIC_DISCORD_WS_URL: ${{ vars.PUBLIC_DISCORD_WS_URL }}
          PUBLIC_MODE: ${{ vars.PUBLIC_MODE }}
          # mailer service
          ISC_WWW_CLIENT_ID: ${{ vars.ISC_WWW_CLIENT_ID }}
          ISC_MAILER_CLIENT_ID: ${{ vars.ISC_MAILER_CLIENT_ID }}
          ISC_QR_CLIENT_ID: ${{ vars.ISC_QR_CLIENT_ID }}
          MAILER_SERVICE_URL: ${{ vars.MAILER_SERVICE_URL }}
          # qr service
          # TODO: rotate JWT_SECRET after 2024.04.20 (meetup event)
          QR_JWT_SECRET: ${{ secrets.QR_JWT_SECRET }}
          QR_SERVICE_URL: ${{ vars.QR_SERVICE_URL }}

      - name: Deploy to Cloudflare
        id: cloudflare-pages-deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sveltevietnam
          directory: sites/www/.svelte-kit/cloudflare
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: |-
            ${{
              needs.pre_jobs.outputs.mode == 'production' && 'production'
            || needs.pre_jobs.outputs.mode == 'preview' && 'preview'
            || github.ref_name
            }}

      - name: Create commit comment
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/commit-comment@v3
        with:
          body: |
            ## ⚡ Successfully Cloudflare Pages deployed!
            | Name | Link |
            | :--- | :--- |
            | Latest commit | ${{ github.event.pull_request.head.sha || github.sha }} |
            | Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | Deploy Preview Url | [${{ needs.pre_jobs.outputs.mode == 'preview' && 'https://preview.sveltevietnam.dev' || steps.cloudflare-pages-deploy.outputs.url }}](${{ needs.pre_jobs.outputs.mode == 'preview' && 'https://preview.sveltevietnam.dev' || steps.cloudflare-pages-deploy.outputs.url }}) |
            | Environment | ${{ needs.pre_jobs.outputs.mode }} |

      - name: Create PR comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: www
          message: |
            ## ⚡ Successfully Cloudflare Pages deployed!
            | Name | Link |
            | :--- | :--- |
            | Latest commit | ${{ github.event.pull_request.head.sha || github.sha }} |
            | Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | Deploy Preview Url | [${{ needs.pre_jobs.outputs.mode == 'preview' && 'https://preview.sveltevietnam.dev' || steps.cloudflare-pages-deploy.outputs.url }}](${{ needs.pre_jobs.outputs.mode == 'preview' && 'https://preview.sveltevietnam.dev' || steps.cloudflare-pages-deploy.outputs.url }}) |
            | Environment | ${{ needs.pre_jobs.outputs.mode }} |
